---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-platform-discovery-server
  labels:
    app: ecommerce-platform-discovery-server
spec:
  type: NodePort
  selector:
    app: ecommerce-platform-discovery-server
  ports:
    - protocol: TCP
      port: 8761
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-platform-discovery-server
spec:
  selector:
    matchLabels:
      app: ecommerce-platform-discovery-server
  replicas: 1
  template:
    metadata:
      labels:
        app: ecommerce-platform-discovery-server
    spec:
      containers:
        - name: ecommerce-platform-discovery-server
          image: asen311/ecommerce-discovery-server-image:1.0.0
          ports:
            - containerPort: 8761
          livenessProbe:
            httpGet:
              path: /health
              port: 8761
            initialDelaySeconds: 30
            timeoutSeconds: 1
